import type { NodeType } from '@cslab/engine';
import {
  AppWindow,
  Archive,
  Boxes,
  BrickWall,
  Braces,
  Box,
  Cloud,
  Cpu,
  Database,
  Factory,
  Fingerprint,
  FolderOpen,
  Globe,
  KeyRound,
  Laptop,
  LayoutGrid,
  Monitor,
  Network,
  Router,
  Server,
  ShieldHalf,
  type LucideIcon,
} from 'lucide-react';

export const NODE_ICONS: Record<NodeType, LucideIcon> = {
  internet: Globe,
  router: Router,
  firewall: BrickWall,
  workstation: Monitor,
  laptop: Laptop,
  server: Server,
  'web-server': AppWindow,
  'api-server': Braces,
  database: Database,
  'file-share': FolderOpen,
  'cloud-service': Cloud,
  container: Box,
  'k8s-cluster': Boxes,
  'iot-device': Cpu,
  plc: Factory,
  'domain-controller': Network,
  'identity-provider': Fingerprint,
  'vpn-gateway': ShieldHalf,
  'jump-host': KeyRound,
  'backup-server': Archive,
  'saas-app': LayoutGrid,
};
